<?xml version="1.0" encoding="utf-8"?><Database Name="Timekeeping" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost,1433;Initial Catalog=Timekeeping;Persist Security Info=True;User ID=sa" SettingsObjectName="winform_project.Properties.Settings" SettingsPropertyName="TimekeepingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Schedules" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="start_work_hour" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_work_hour" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_holiday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_weekend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="employee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Schedule" Member="Employee" ThisKey="employee_id" OtherKey="id" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Departments" Member="Departments">
    <Type Name="Department">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="id" OtherKey="department_id" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="salary" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="position_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="department_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Schedule" Member="Schedules" ThisKey="id" OtherKey="employee_id" Type="Schedule" />
      <Association Name="Department_Employee" Member="Department" ThisKey="department_id" OtherKey="id" Type="Department" IsForeignKey="true" />
      <Association Name="Position_Employee" Member="Position" ThisKey="position_id" OtherKey="id" Type="Position" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Positions" Member="Positions">
    <Type Name="Position">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Position_Employee" Member="Employees" ThisKey="id" OtherKey="position_id" Type="Employee" />
    </Type>
  </Table>
</Database>