<?xml version="1.0" encoding="utf-8"?><Database Name="Timekeeping" Class="TimekeepingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost,1433;Initial Catalog=Timekeeping;Persist Security Info=True;User ID=sa" SettingsObjectName="winform_project.Properties.Settings" SettingsPropertyName="TimekeepingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Approvals" Member="Approvals">
    <Type Name="Approval">
      <Column Name="approval_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="employee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Approval" Member="Employee" ThisKey="employee_id" OtherKey="employee_id" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedules" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="schedule_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="working_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="is_holiday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_weekend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="workday" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="start_work_hour" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_work_hour" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hour_work_late" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hour_leave_early" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="employee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Schedule" Member="Employee" ThisKey="employee_id" OtherKey="employee_id" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="employee_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="position_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="coefficients_salary" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Approval" Member="Approvals" ThisKey="employee_id" OtherKey="employee_id" Type="Approval" />
      <Association Name="Employee_Schedule" Member="Schedules" ThisKey="employee_id" OtherKey="employee_id" Type="Schedule" />
      <Association Name="Position_Employee" Member="Position" ThisKey="position_id" OtherKey="position_id" Type="Position" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Holidays" Member="Holidays">
    <Type Name="Holiday">
      <Column Name="holiday_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="start_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="end_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Positions" Member="Positions">
    <Type Name="Position">
      <Column Name="position_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="basic_salary" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Position_Employee" Member="Employees" ThisKey="position_id" OtherKey="position_id" Type="Employee" />
    </Type>
  </Table>
  <Function Name="dbo.sp_createEmployee" Method="sp_createEmployee">
    <Parameter Name="_name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="_email" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="_password" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="_phone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="_address" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="_birthday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="_gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="_coefficients_salary" Type="System.Double" DbType="Float" />
    <Parameter Name="_avatar" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="_position_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="_outStt" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="_outMsg" Type="System.String" DbType="NVarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_loadSchedule" Method="sp_loadSchedule">
    <Parameter Name="_employee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="_working_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="_start_work_hour" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="_end_work_hour" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="_outStt" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="_outMsg" Type="System.String" DbType="NVarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_createPosition" Method="sp_createPosition">
    <Parameter Name="_name" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="_basic_salary" Type="System.Double" DbType="Float" />
    <Parameter Name="_outStt" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="_outMsg" Type="System.String" DbType="NVarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_getAllSchedulesByEmployeeId" Method="sp_getAllSchedulesByEmployeeId">
    <Parameter Name="_employee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="_working_month" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_getAllSchedulesByEmployeeIdResult">
      <Column Name="schedule_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="working_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="is_holiday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="is_weekend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="workday" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="start_work_hour" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_work_hour" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hour_work_late" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hour_leave_early" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="employee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_insertHoliday" Method="sp_insertHoliday">
    <Parameter Name="_start_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="_end_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="_description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="_outStt" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="_outMsg" Type="System.String" DbType="NVarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_countAllSchedulesByEmployeeId" Method="sp_countAllSchedulesByEmployeeId">
    <Parameter Name="_employee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="_working_month" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_countAllSchedulesByEmployeeIdResult">
      <Column Name="total_workday" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="total_hour_work_late" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_hour_leave_early" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_holiday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_weekend" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_deleteEmployee" Method="sp_deleteEmployee">
    <Parameter Name="_employee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="_outStt" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="_outMsg" Type="System.String" DbType="NVarChar(200)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>